version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
  nginx:
    image: nginx:1.19
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web